### ISSUE TITLE
Runtime Exception in EqualizerActivity

### ISSUE THREAD

**Issue by archrival** [archrival/Subsonic-Android#2]
Exceptions similar to this can occur when creating the equalizer, will try to catch them from now on.

java.lang.RuntimeException: Unable to start activity
Caused by: java.lang.RuntimeException: AudioEffect: set/get parameter error
at android.media.audiofx.AudioEffect.checkStatus(AudioEffect.java:1231)
at android.media.audiofx.Equalizer.getBandLevelRange(Equalizer.java:207)
at com.thejoshwa.ultrasonic.androidapp.activity.EqualizerActivity.initEqualizer(EqualizerActivity.java:135)
at com.thejoshwa.ultrasonic.androidapp.activity.EqualizerActivity.onCreate(EqualizerActivity.java:61)

**Comment by Alfred-Francis** [comment]
Hi, I have the same issue with ICS. 
With some research I found that it happens only when AudioFocusChangeListener is implemented. 
The Equalizer is not getting initialized for some reason.
One point noteworthy is every second launch it works properly.
